#!/bin/bash

#CONF
set -e -x
cat <<EOF > /usr/sbin/policy-rc.d
#!/bin/sh
exit 101
EOF
chmod +x /usr/sbin/policy-rc.d

cat <<EOF > /usr/sbin/invoke-rc.d
#!/bin/sh
exit 0
EOF
chmod +x /usr/sbin/invoke-rc.d

cat <<EOF > /etc/apt/sources.list
deb http://ftp.free.fr/mirrors/ftp.ubuntu.com/ubuntu/ quantal main restricted
deb http://security.ubuntu.com/ubuntu quantal-security main restricted
deb http://ftp.free.fr/mirrors/ftp.ubuntu.com/ubuntu/ quantal-updates main restricted

deb http://ftp.free.fr/mirrors/ftp.ubuntu.com/ubuntu/ quantal universe multiverse
deb http://security.ubuntu.com/ubuntu quantal-security universe multiverse
deb http://ftp.free.fr/mirrors/ftp.ubuntu.com/ubuntu/ quantal-updates universe multiverse
EOF

cat <<EOF > /etc/mtab
rootfs / rootfs rw 0 0
EOF

sed '/127\.0\.1\.1/d' /etc/hosts
cat <<EOF > /etc/hosts
127.0.1.1 gitorious
EOF

cat <<EOF > /etc/apt/apt.conf.d/70debconf
// Pre-configure all packages with debconf before they are installed.
// If you don't like it, comment it out.
// DPkg::Pre-Install-Pkgs {"/usr/sbin/dpkg-preconfigure --apt || true";};
EOF

set +e +x

apt-get update
apt-get upgrade -y
apt-get install -y git-core apg build-essential libpcre3 libpcre3-dev postfix make zlib1g zlib1g-dev ssh libc6-dev libssl-dev libmysql++-dev libmysqlclient-dev libsqlite3-dev libreadline-dev libonig-dev libyaml-dev geoip-bin libgeoip-dev libgeoip1 imagemagick mysql-client mysql-server libmysqlclient-dev sphinxsearch memcached apache2
