#!/bin/bash

echo "Reload conf ..."
initctl reload-configuration
echo "Stop Git Daemon ..."
su - git bash -c 'cd gitorious; kill $(cat log/git-daemon.pid)' &> /dev/null
echo "Start Git Daemon ..."
su - git bash -c 'cd gitorious; RAILS_ENV=production script/git-daemon -d' &> /dev/null
echo "Stop Stomp ..."
su - git bash -c 'cd gitorious; kill $(cat log/stompserver.pid)' &> /dev/null
echo "Start Stomp ..."
su - git bash -c 'cd gitorious; RAILS_ENV=production stompserver -w tmp/stomp -q file -s queue& echo $! > log/stompserver.pid' &> /dev/null
echo "Stop poller ..."
su - git bash -c 'cd gitorious; mkdir -p tmp/pids; RAILS_ENV=production script/poller stop' &> /dev/null
echo "Start poller ..."
su - git bash -c 'cd gitorious; mkdir -p tmp/pids; RAILS_ENV=production script/poller start' &> /dev/null
echo "Stop ultrasphinx ..."
su - git bash -c 'cd gitorious; RAILS_ENV=production rake ultrasphinx:daemon:stop' &> /dev/null
echo "Start ultrasphinx ..."
su - git bash -c 'cd gitorious; RAILS_ENV=production rake ultrasphinx:daemon:start' &> /dev/null

